spring:
  application:
    name: bank-management-system
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bank_management}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}

server:
  port: 8080

logging:
  level:
    com.bankmanagement: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-here-make-it-long-and-secure-in-production}
  expiration: 86400000 # 24 hours in milliseconds

# Supabase Configuration
supabase:
  url: ${SUPABASE_URL:}
  anon-key: ${SUPABASE_ANON_KEY:}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY:}
